### ISSUE TITLE
Support approveChatJoinRequest

### ISSUE THREAD

**Issue by winstonsung** [The-Earth/catbot#1]
## Type(s) needed to be supported

* `approveChatJoinRequest`

## Needed by

* https://github.com/The-Earth/Telegram-MediaWiki-Confirm-Bot
  * translatewiki.net-zh Telegram group

## References

* <https://core.telegram.org/bots/api#approvechatjoinrequest>

----

## CC

* @The-Earth

**Comment by winstonsung** [comment]
> In <https://t.me/twn_zh/13026> , **SunAfterRain** wrote:
> 您跟大貓老師說 https://github.com/sunafterrainwm/catbot/commit/b9f8017f543e4cf785d7f723843a37680d6b7b18 可以參考一下

----

CC: @The-Earth

**Comment by The-Earth** [comment]
Pull request filed
